# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d2819f89ed40b3925a9e1bd2db8c984e"
name = "flexi-fields"
application_url = "https://flexi-fields.degvora.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,write_products,read_customer_payment_methods,write_own_subscription_contracts"

[auth]
redirect_urls = [ "https://flexi-fields.degvora.com/auth/callback" ]
